### PR TITLE
CachedNetworkImage and BlurHash added (Like is not working as of now) modal added

### PR DESCRIPTION
**Pull request by girish54321**
Adding image blur_hash and use provider ,sql for like image..

### CODE REVIEW

**Comment by Singh-Shivani** [comment]
Hello Girish! Thank you for the PR, I eyegazed the code, seems good but to try it to out I'm merging into a different branch. Also apologies for the late reply, I'll merge it into master after testing out the code.

**Comment by Singh-Shivani** [comment]
Hello Girish! Firstly I would like to **congratulate you for the amazing work and effort** you put in this app, I really appreciate!

I checked everything and ran the app, it seems really good for me. Apart from functionalities which are done perfectly I would like to give you a legit feedback so that we both can grow as a Dev.
There are some parts of the app or to be more specific the UI part which doesn't go with the app flow. Some buttons(eg. like button) or small things which gives extra effect and ease to go should be placed properly. So I'm merging the test branch with master. I would like to do some changes in the UI, I'll do that part later after merging. Anything else you want to ask or want me to know? I would love to hear your view as well.
Thanks!

**Comment by girish54321** [comment]
Hi @Singh-Shivani 
Thanks for your legit feedback and i agree with you.

**Comment by Singh-Shivani** [comment]
Alright! I'll be merging the test branch with master and will do changes in the UI afterwards. Thanks for the efforts!

**Comment by girish54321** [comment]
Hi, @Singh-Shivani I made some more changes to the repo but I need your help in making it responsive for the desktop.
can you help me 😋
[`repo link`](https://github.com/girish54321/Chitr)

**Comment by Singh-Shivani** [comment]
Sure! I really appreciate your efforts!

**Comment by girish54321** [comment]
Can you try running my repo on windows pc or mac and see how can we make this more responsive 
as of now anytime I resize the window it reloads the screen 🤕
note: Windows desktop app is not tested 😅

**Comment by Singh-Shivani** [comment]
Ohhh I'm so sorry but I own a Linux machine! 😕

**Comment by girish54321** [comment]
Oh that's a bummer 🤕
anyway if you found any resources about **responsive** do share 👍

**Comment by Singh-Shivani** [comment]
Yess Sure!!

**Pull request merged**
