### PR TITLE
Mac OS Support added  🎉

### PR DESCRIPTION
**Pull request by girish54321**
Hi i have added mac OS support & update code with new UI 😁.

### CODE REVIEW

**Comment by Singh-Shivani** [comment]
That's awesome!! Thank you so much for your help towards this repository. I
really appreciate this.

**Comment by Singh-Shivani** [comment]
You can add a readme file including new UI working app and screen images.
Later I'll include that in main readme file.

**Comment by Singh-Shivani** [comment]
> Hi i have added mac OS support & update code with new UI 😁.

Amazing Work @girish54321 !! 🎉🎉🎉

**Comment by girish54321** [comment]
Hi, @Singh-Shivani I will include that in read me. 👍

**Comment by Singh-Shivani** [comment]
Thankss! I'm looking forward to it. 💯

**Comment by girish54321** [comment]
Hey @Singh-Shivani 
added app video (gif in read me) ☑️

**Comment by Singh-Shivani** [comment]
Hello @girish54321 I have merged your code and it looks so good! Amazing work, Congratulations!

**Comment by Singh-Shivani** [comment]
If you can find some other color in the place of purple in light theme or just keep it white...I think it would look nice! Other than that, all good. @girish54321 🔥

**Comment by girish54321** [comment]
lol @Singh-Shivani you don't like `purple` 😅
I don't know what color to pick what's your suggestion for color 

Plz no white 😝

**Comment by Singh-Shivani** [comment]
Purple doesn't go well with this scheme I guess, white looks sophisticated
if you can keep that it will look nice I guess. Apart from white you can go
for some bright color if not white.

**Pull request merged**
